# Generated by Django 4.2.7 on 2024-01-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_type', models.CharField(choices=[('pizza', 'Pizza'), ('burger', 'Burger'), ('sandwich', 'Sandwich'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], max_length=10)),
                ('item_image', models.ImageField(upload_to='media/food_item_images/')),
            ],
        ),
    ]
